name: api_client
description: Generates a client for a RESTful API.
version: 1.0.0
repository: https://github.com/Ownii/api-client

environment:
  sdk: ^3.5.0-152

dependencies:
  macros: ^0.1.0-main.5
  json: ^0.20.2
  dio: ^5.5.0+1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
